name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Check Renovate config
        run: pnpm run test

      - name: Test Renovate config
        run: |
          pnpm exec renovate \
              --dry-run \
              --schedule= \
              --require-config=ignored \
              '${{ github.repository }}'
        env:
          RENOVATE_USERNAME: renovate[bot]
          RENOVATE_GIT_AUTHOR: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
          RENOVATE_TOKEN: ${{ github.token }}
          RENOVATE_BASE_BRANCHES: ${{ github.sha }}
          RENOVATE_CONFIG_FILE: ./renovate.json
          LOG_LEVEL: debug
